server:
  port: 9090
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/books/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/carts/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
  application:
    name: gateway-service

  banner:
    location: banner.txt


